version: "3.9"

services:
  db-container:
    container_name: "db"
    image: postgres:alpine
    environment:
       POSTGRES_USER : "sofianebraneci"
       POSTGRES_HOST_AUTH_METHOD : "trust"
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db-container
    ports:
      - "8081:8081"
    environment:
       SPRING_DATASOURCE_URL : "jdbc:postgresql://db:5432/student"
       SPRING_DATASOURCE_USERNAME : "sofianebraneci"
       SPRING_JPA_HIBERNATE_DDL_AUTO : "create-drop"

